{
 "title": "KeyvDB Metrics",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "No. of Keys",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "no_of_key" }
   ]
  },
  {
   "title": "No. of Endpoint Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "by_endpoint_counter_total", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Average Latency by Endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Live Requests by Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests_by_status_sum", "legendFormat": "{{ status }}" }
   ]
  }
 ]
}