apiVersion: v1
kind: Service
metadata:
  name: keyvdb-sample-service
  namespace: default
  labels:
    app: keyvdb
spec:
  type: NodePort
  selector:
    app: keyvdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
      nodePort: 30006