{
 "title": "KeyvDB Metrics",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "No. of Keys",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "no_of_key" }
   ]
  },
  {
   "title": "No. of Endpoint Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "by_endpoint_counter_total", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Request rate per Endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(request_count_total[5m])" }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}